/*
** EPITECH PROJECT, 2025
** coding-style-war-crimes
** File description:
** exception_types
*/

#ifndef EXCEPTION_TYPES_H_
    #define EXCEPTION_TYPES_H_
    #include <setjmp.h>
    #include <stdbool.h>
    #include "../../include/types.h"

    #define __C_EXTEND_EXCEPTION_CONTEXT_ALIGNMENT 16

typedef enum {
    C_EXTEND_EXCEPTION = 0,

    C_EXTEND_EXCEPTION_LOGIC_ERROR,
    C_EXTEND_EXCEPTION_INVALID_ARGUMENT,
    C_EXTEND_EXCEPTION_DOMAIN_ERROR,
    C_EXTEND_EXCEPTION_LENGTH_ERROR,
    C_EXTEND_EXCEPTION_OUT_OF_RANGE,
    C_EXTEND_EXCEPTION_FUTURE_ERROR,
    C_EXTEND_EXCEPTION_LOGIC_ERROR_MAX,

    C_EXTEND_EXCEPTION_RUNTIME_ERROR,
    C_EXTEND_EXCEPTION_RANGE_ERROR,
    C_EXTEND_EXCEPTION_OVERFLOW_ERROR,
    C_EXTEND_EXCEPTION_UNDERFLOW_ERROR,
    C_EXTEND_EXCEPTION_REGEX_ERROR,
    C_EXTEND_EXCEPTION_SYSTEM_ERROR,
    C_EXTEND_EXCEPTION_TX_EXCEPTION,
    C_EXTEND_EXCEPTION_NONEXISTENT_LOCAL_TIME,
    C_EXTEND_EXCEPTION_AMBIGUOUS_LOCAL_TIME,
    C_EXTEND_EXCEPTION_FORMAT_ERROR,
    C_EXTEND_EXCEPTION_RUNTIME_ERROR_MAX,

    C_EXTEND_EXCEPTION_BAD_TYPE,
    C_EXTEND_EXCEPTION_BAD_TYPEID,
    C_EXTEND_EXCEPTION_BAD_CAST,

    C_EXTEND_EXCEPTION_BAD_FUNCTION_CALL,

    C_EXTEND_EXCEPTION_BAD_ALLOC,
    C_EXTEND_EXCEPTION_BAD_ARRAY_NEW_LENGTH,
    C_EXTEND_EXCEPTION_BAD_ALLOC_MAX,

    C_EXTEND_EXCEPTION_BAD_EXCEPTION,

    C_EXTEND_EXCEPTION_MAX
} c_extend_exception_types_t;

struct __attribute__((aligned(__C_EXTEND_EXCEPTION_CONTEXT_ALIGNMENT)))
    c_extend_exception_context_s {
    sigjmp_buf __env;
    c_extend_private_t __internals;
};

typedef struct c_extend_exception_context_s c_extend_exception_context_t;

typedef vint_t c_extend_exception_code_t;

#endif /* !EXCEPTION_TYPES_H_ */
